main: me.pixelmania.wolfpolice.main.Core
name: WolfPolice
version: 1.0.2c
author: Patty_Mayo

api-version: 1.12.2

depend: [SimpleJail, PermissionsEx]
softdepend: [SkinsRestorer]

commands:
   police:
      usage: |
         usage: /<command> tp <player>
         usage: /<command> <player> demote citizen
         usage: /<command> <player> promote jrpolice/srpolice
   additems:
      usage: /<command>
   getbaton:
      usage: /<command>
   release:
      usage: /<command> <player>
   pc:
      usage: /<command> <message>
   duty:
      usage: /<command>
   incidents:
      usage: /<command> <player>
   wpd:
      usage: /<command>
   policesay:
      usage: /<command> <message>
   pctoggle:
      usage: /<command> toggle
